import { useState } from 'react';
import { FlatList, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { Button, Card, Chip, HelperText, Surface, Text, TextInput } from 'react-native-paper';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTableScoreStore } from '@/stores/useTableScoreStore';

export default function DashboardScreen() {
  const [username, setUsername] = useState(''); const [tableName, setTableName] = useState('');
  const store = useTableScoreStore();
  const importCollection = async () => { if (username.trim()) try { await store.loadCollection(username); } catch {} };
  const createTable = async () => { try { await store.createTable(tableName); } catch {} };
  return <SafeAreaView style={s.safe} edges={['top']}><FlatList data={store.collection.slice(0, 3)} keyExtractor={(game) => String(game.bggId)} contentContainerStyle={s.content}
    ListHeaderComponent={<><LinearGradient colors={['#271B36', '#6750A4', '#8B70C9']} style={s.hero}><Text variant="labelLarge" style={s.eyebrow}>GAME NIGHT, SORTED</Text><Text variant="displaySmall" style={s.heroTitle}>Make every{`\n`}score count.</Text><Text variant="bodyLarge" style={s.heroCopy}>Build a shared table, track every point, and keep game night moving.</Text><Button mode="contained" buttonColor="#E9DDFF" textColor="#3A245E" icon="play" onPress={() => store.table ? router.push('/sessions/new') : undefined}>{store.table ? 'Start a game' : 'Create a table below'}</Button></LinearGradient>
      <View style={s.heading}><Text variant="titleLarge">Tonight&apos;s table</Text><Chip icon="account-group">{store.table ? 'Ready' : 'Not started'}</Chip></View><Surface elevation={1} style={s.panel}>{store.table ? <><Text variant="titleLarge">{store.table.name || 'Game night'}</Text><Text style={s.muted}>Share this with your group</Text><View style={s.code}><Text variant="labelSmall">TABLE CODE</Text><Text variant="headlineMedium">{store.table.code}</Text></View><Button mode="contained" icon="play" onPress={() => router.push('/sessions/new')}>Start scoring</Button></> : <><Text variant="titleMedium">Start anonymously</Text><Text style={s.muted}>No sign-up. Just create a code for this table.</Text><TextInput label="Table name" placeholder="Friday game night" value={tableName} onChangeText={setTableName} mode="outlined" /><Button mode="contained" icon="table-furniture" loading={store.isCreatingTable} onPress={createTable}>Create table</Button></>}</Surface>
      <View style={s.heading}><Text variant="titleLarge">Quick actions</Text></View><View style={s.actions}><Card mode="contained" style={s.action} onPress={() => router.push('/rules/new')}><Card.Content><Text variant="headlineSmall">＋</Text><Text variant="titleMedium">Scoring sheet</Text><Text variant="bodySmall">Build your own</Text></Card.Content></Card><Card mode="contained" style={s.action} onPress={() => router.push('/library')}><Card.Content><Text variant="headlineSmall">⌘</Text><Text variant="titleMedium">Your library</Text><Text variant="bodySmall">Import from BGG</Text></Card.Content></Card></View>
      <View style={s.heading}><Text variant="titleLarge">Bring your games</Text><Chip>{store.collection.length} imported</Chip></View><Surface elevation={0} style={s.import}><Text style={s.muted}>Connect BoardGameGeek to see your collection here.</Text><TextInput label="BGG username" value={username} onChangeText={setUsername} autoCapitalize="none" mode="outlined" /><Button mode="outlined" icon="download" loading={store.isLoadingCollection} disabled={!username.trim()} onPress={importCollection}>Import collection</Button></Surface>{store.error && <HelperText type="error" visible>{store.error}</HelperText>}{store.collectionStatus && <HelperText type="info" visible>{store.collectionStatus}</HelperText>}{store.collection.length > 0 && <Text variant="titleMedium" style={s.recent}>Recently imported</Text>}</>}
    renderItem={({ item }) => <Card mode="outlined" style={s.game}><Card.Content><Text variant="titleMedium">{item.name}</Text><Text variant="bodySmall" style={s.muted}>{item.yearPublished || 'Unknown year'} · {item.minPlayers ?? '?'}–{item.maxPlayers ?? '?'} players · {item.playingTime ?? '?'} min</Text></Card.Content></Card>}
  /></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#FFFBFE' }, content: { gap: 14, paddingBottom: 30 }, hero: { borderBottomLeftRadius: 30, borderBottomRightRadius: 30, gap: 12, padding: 24, paddingBottom: 28 }, eyebrow: { color: '#E9DDFF', letterSpacing: 1.2 }, heroTitle: { color: '#FFF7FF', fontWeight: '700' }, heroCopy: { color: '#F5EEFF', lineHeight: 22 }, heading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginHorizontal: 20, marginTop: 10 }, panel: { backgroundColor: '#FFF7FF', borderRadius: 24, gap: 12, marginHorizontal: 20, padding: 18 }, muted: { color: '#655D6D', marginTop: 4 }, code: { alignItems: 'center', backgroundColor: '#E9DDFF', borderRadius: 16, gap: 2, padding: 12 }, actions: { flexDirection: 'row', gap: 12, marginHorizontal: 20 }, action: { backgroundColor: '#EEE8F2', flex: 1 }, import: { backgroundColor: '#F7F2FA', borderRadius: 20, gap: 12, marginHorizontal: 20, padding: 16 }, recent: { marginHorizontal: 20 }, game: { marginHorizontal: 20 } });
